name: lunar-e2e-pin-rotation-cb4f55212
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened cb4f55212'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-cb4f55212'
    runs-on: localdev-e2e-test-37915228467-1-github-2-e2e
    steps:
      - run: /bin/echo 'pin rotation CI cb4f55212'
