name: lunar-e2e-pin-rotation-e10ddc0f2
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened e10ddc0f2'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-e10ddc0f2'
    runs-on: localdev-e2e-test-37984014193-1-github-2-e2e
    steps:
      - run: /bin/echo 'pin rotation CI e10ddc0f2'
